name: downloading_manager
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.4.0
  get_it: ^8.0.3
  go_router: ^15.1.1
  internet_connection_checker_plus: ^2.7.1
  intl: ^0.20.2
  logger: ^2.5.0
  objectbox: ^4.1.0
  objectbox_flutter_libs: any
  pinput: ^5.0.1
  shared_preferences: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#121212"
  image: assets/images/splash_logo.png
  android: true
  ios: true
  android_12:
    color: "#121212"
    image: assets/images/splash_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 24 # android min sdk min:16, default 21
